//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jobfinder_back.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Funcion
    {
        public int id { get; set; }
        public string descripcion { get; set; }
        public int oferta_id { get; set; }

        [JsonIgnore]
        public virtual Oferta Oferta { get; set; }
    }
}
