//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jobfinder_back.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gestion
    {
        public int id { get; set; }
        public int empleador_id { get; set; }
        public int administrador_id { get; set; }
        public int oferta_id { get; set; }
    
        public virtual Administrador Administrador { get; set; }
        public virtual Empleador Empleador { get; set; }
        public virtual Oferta Oferta { get; set; }
    }
}
